### ISSUE TITLE
Dialog does not fit on the screen

### ISSUE THREAD

**Issue by MaciejCzekanski** [wdullaer/MaterialDateTimePicker#17]
It looks like fonts used are a bit too big (at least for my phone). Title gets cropped and it looks bad. You can compare it with date picker in Inbox.

I use Galaxy Nexus (4.65" screen @ 1280x720) running Android 5.1.
![screenshot_2015-04-13-11-28-34](https://cloud.githubusercontent.com/assets/1592892/7113118/d7256b22-e1d0-11e4-9af7-7be4ffed79a3.png)
![screenshot_2015-04-13-11-28-27](https://cloud.githubusercontent.com/assets/1592892/7113119/d74a784a-e1d0-11e4-9aa4-a9bd0c0f026e.png)

**Comment by geecko86** [comment]
@wdullaer: I managed to reproduce this on an emulator. It happens with 1.2.+.

**Comment by wdullaer** [comment]
Judging by the screenshot, there is enough place on the gnex for the full datepicker.
I'm guessing some xml value is specified in pixels instead of dp.

I could probably shrink the entire size of the picker by reducing the margins on the top bit.
I'll have to experiment a bit here.

**Comment by wdullaer** [comment]
I just dusted off my gnex running 4.3 and I can't reproduce this.

**Comment by geecko86** [comment]
That's because he's running an unofficial/unstable 5.1 rom. However it's
unrelated to the rom, since the emulator has the issue as well.

**Comment by MaciejCzekanski** [comment]
Yes, it's an unofficial build, but its based on AOSP, with very little modifications, so I guess the bug will occur also on different devices.

**Comment by wdullaer** [comment]
Can you test v1.2.2
I can't reproduce it, so I'm not 100% sure it's fixed.

**Comment by geecko86** [comment]
Looks like it is! 

However I noticed that in lanscape, the OK button was a bit off. It looks like the bottom is cut off. Don't know if this is new.

![Here](https://puu.sh/hgGyM.png)

**Comment by wdullaer** [comment]
This is a similar issue to the one I just solved in portrait.
Again, it doesn't happen on my gnex on 4.3

I have the impression that android resolves `match_parent` to something slightly larger than the actual screen on lollipop. At least for a gnex.

**Comment by MaciejCzekanski** [comment]
Hi,

it still happens on my phone. Here's fresh screenshot:

![screenshot_2015-04-17-12-19-20](https://cloud.githubusercontent.com/assets/1592892/7200310/16d9b6e6-e4fc-11e4-8772-be7b5d347237.png)

**Comment by MaciejCzekanski** [comment]
Sorry, it looks like the new version wasn't used. I cleand the project and it looks better now:

![screenshot_2015-04-17-12-25-17](https://cloud.githubusercontent.com/assets/1592892/7200424/029498a8-e4fd-11e4-90a2-1f59f8587144.png)

**Comment by wdullaer** [comment]
Do you have that same issue in landscape on your phone?

**Comment by wdullaer** [comment]
Release 1.3.1 should fix this.
Can you let me know if this is the case?

**Comment by MaciejCzekanski** [comment]
Looks much better now, both in portrait&landscape. Thanks.

**Comment by wdullaer** [comment]
Great news.
I'm going to close this issue for now.
