### ISSUE TITLE
No spacing under the year?

### ISSUE THREAD

**Issue by Jdruwe** [wdullaer/MaterialDateTimePicker#25]
Hey!

First of all, thanks for this great library! I am having this weird issue where there is no spacing under the year:

![date_picker_bug](https://cloud.githubusercontent.com/assets/4804496/7532401/b4cb28a6-f566-11e4-8810-1bf0284cc518.png)

Is there a way to fix this?

**Comment by wdullaer** [comment]
Something is still wrong with the spacing in some cases. See also #17 
I'm still experimenting to see how I can resolve this.

**Comment by wdullaer** [comment]
Release 1.3.1 should fix this.
Can you let me know if this is the case?

**Comment by Jdruwe** [comment]
Sorry for my late answer! I updated the gradle lib version but I am still experiencing the issue:

<img src="https://cloud.githubusercontent.com/assets/4804496/8084497/a3efc8cc-0f8b-11e5-999c-cbf6dc2be8c6.png" width="400"/>

**Comment by wdullaer** [comment]
It doesn't look like it has improved a single pixel, even though I reduced some of the spacings.
Can you give me some more information:
* What device are you testing this on?
* What resolution does the device have?
* Are you overwriting some default margins/dimensions?

I really can't reproduce this behavior here

**Comment by Jdruwe** [comment]
Device: OnePlus One
Resolution: 1080 x 1920 pixels (~401 ppi pixel density)

This is the code that gets called when clicking an edittext to open the date picker:

```java 
    private void openDatePickerDialog() {
        Calendar now = Calendar.getInstance();
        if (selectedBirthDate != null) {
            now.setTime(selectedBirthDate);
        }

        DatePickerDialog dpd = DatePickerDialog.newInstance(
                this,
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH)
        );

        Calendar cal = Calendar.getInstance();
        dpd.setMaxDate(cal);
        dpd.show(getActivity().getFragmentManager(), "Datepickerdialog");
    }
```

**Comment by wdullaer** [comment]
I test on exactly the same device (among others) and don't have this issue.
I think that you might (not deliberately) be overwriting some layout parameter in your parent app.

Could you compile the sample app include with this repository and let me know if the year layout issue is still present?
